name: Build and Release

on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.0.2

permissions:
  contents: write # Fixes the 403 error by allowing the bot to create releases

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: bin/mar
            asset_name: mar-linux-x86_64
          - os: macos-latest
            artifact_name: bin/mar
            asset_name: mar-macos-arm64
          - os: windows-latest
            artifact_name: bin/mar.exe
            asset_name: mar-windows-x64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Mar Compiler
        run: make # Compiles your code using your Makefile

      - name: Rename binary for release
        shell: bash
        # We use the full path 'bin/' so the runner can find your file
        run: mv ${{ matrix.artifact_name }} ${{ matrix.asset_name }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Built-in token